### ISSUE TITLE
Argument spelling in cs-orchestra

### ISSUE THREAD

**Issue by j-bresson** [openmusic-project/OM2Csound#1]
The symbol `rigth` is misspelled in all the cs-orchestra.lisp functions (should be "right" !).

Fixing it might cause compatibility issues, with patches that already have boxes set with this wrong spelling as input value.

I think we could do it anyway, as users of these "orc" boxes are not thousands.

**Comment by ma-stro** [comment]
Dear Jean,
Wouldn't it be possible to create an alias (right = rigth) in order to preserve backward compatibility with previous users? They are certainly not thousand, but those who will have problems might complain.Just a simple idea.Marco
    Am Mittwoch, 18. November 2020, 00:56:44 MEZ hat Jean Bresson <notifications@github.com> Folgendes geschrieben:  
 
 


The symbol rigth is misspelled in all the cs-orchestra.lisp functions (should be "right" !).

Fixing it might cause compatibility issues, with patches that already have boxes set with this wrong spelling as input value.

I think we could do it anyway, as users of these "orc" boxes are not thousands.

**Comment by j-bresson** [comment]
Yes. There exist solutions if we want to be on the safe side :)

**Comment by j-bresson** [comment]
ok, I think this is fixed in 57d3cf0d1491f840e94a739d615c0b4a5e39a0f9
